services:
  - type: web
    name: melos-frontend
    image:
      url: ghcr.io/cs-japan-se/fcs-cicd-lab-melos-private/melos-frontend:latest

    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: MOCK_API_URL
        fromService:
          name: melos-mock-api
          type: web
          property: host
      - key: FLASK_SECRET_KEY
        sync: false
      - key: LOGIN_PASSWORD
        sync: false
      - key: DEBUG_PASSWORD
        sync: false
      - key: CS_APP_NAME
        value: melos-frontend
      - key: CS_AIDR_BASE_URL_TEMPLATE
        sync: false
      - key: CS_AIDR_TOKEN
        sync: false

  - type: web
    name: melos-mock-api
    image:
      url: ghcr.io/cs-japan-se/fcs-cicd-lab-melos-private/melos-mock-api:latest
    plan: free
