services:
  - type: web
    name: melos-frontend
    image:
      url: ghcr.io/cs-japan-se/fcs-cicd-lab-melos-private/melos-frontend:latest
      creds:
        fromRegistryCreds:
          name: ghcr-creds
    plan: free
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: MOCK_API_URL
        fromService:
          name: melos-mock-api
          type: web
          property: host
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DEBUG_PASSWORD
        sync: false

  - type: web
    name: melos-mock-api
    image:
      url: ghcr.io/cs-japan-se/fcs-cicd-lab-melos-private/melos-mock-api:latest
      creds:
        fromRegistryCreds:
          name: ghcr-creds
    plan: free

registryCredentials:
  - name: ghcr-creds
    registry: GITHUB
    username: CS-Japan-SE
    authToken:
      sync: false
